### ISSUE TITLE
Добавить учебный курс

### ISSUE THREAD

**Issue by IOWq750** [gtitov/karta#2]
Не хватает курса Грищенко для ФГМ в магистратуре 2 года

**Comment by gtitov** [comment]
@Shur-AA

**Comment by Shur-AA** [comment]
@IOWq750 Уточни, пожалуйста, название - у меня нет его курса в списке от Е.А. Прохоровой

**Comment by IOWq750** [comment]
Компьютерные технологии в геоэкологии для кафедры ФГМ

**Comment by IOWq750** [comment]
Соврал, это магистратура 1 года

**Comment by Shur-AA** [comment]
добавила
