### ISSUE TITLE
Поменять layout страницы О кафедре

### ISSUE THREAD

**Issue by IOWq750** [gtitov/karta#3]
Общую информацию о кафедре показать на странице http://carto.geogr.msu.ru/site/about/, остальные разделы - в виде списка ссылок

**Comment by gtitov** [comment]
сделать можно, выглядеть будет примерно так (альтернатив по внешнему виду пока предложить не могу из-за ограничений темы)
![image](https://user-images.githubusercontent.com/39987349/204133322-07b65731-5bdd-490a-b544-14c36b068fb9.png)

**Comment by tsamsonov** [comment]
Предлагаю структуру пока не менять в таком случае. Ссылки на разделы должны быть в идеале сбоку от основного контента. Внизу плохо, потому что на небольшом экране их можно не увидеть совсем.

**Comment by gtitov** [comment]
Тогда пока закрываем
